baseUrl                = "/"
title                  = "Scratchpad"
theme                  = "iarp"
languageCode           = "en"
defaultContentLanguage = "en-us"
canonifyURLs           = true
copyright              = "╰( ･ ᗜ ･ )╯"  # footer text

# Configure pagination
Paginate     = 10
PaginatePath = "page"


[params]
    description     = "Notes website" # Site's description
    datefmt         = "02 Jan 2006"   # Custom date format
    showfullcontent = false           # Show full content
    math            = true            # Enable Mathjax support

# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags       = "tags"
    categories = "categories"
    series     = "series"

[author]
    name  = "Xyz Zyx"
    email = "xyz@abc.com"

[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "categories"
        name       = "Categories"
        url        = "/categories/"
        weight     = 1

    [[menu.main]]
        identifier = "tags"
        name       = "Tags"
        url        = "/tags/"
        weight     = 2
